name: `Pull Request Title Validator`
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  require-valid-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: pragmatic-tools/pr-title-validator@1.0.0
        with:
          pattern: 'JIRA-\d+.*'